# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2021-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The Storage Policies API allows for viewing of Provider Storage Policies.
  version: "1.0"
  title: Storage Policies API

paths:
  storagePolicy:
    parameters:
      - name: storagePolicyUrn
        in: path
        description: storagePolicyUrn
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: storagepolicy
    get:
      x-vcloud-added-in: "36.0"
      tags:
        - storagePolicy
      summary: Get specified Storage Policy.
      operationId: getStoragePolicy
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/StoragePolicy"

  storagePolicies:
    get:
      x-vcloud-added-in: "36.0"
      tags:
        - storagePolicy
      summary: Get a paged list of all Provider Storage Policies in the system
      description: |
        Get a paged list of all Provider Storage Policies in the system
      operationId: getStoragePolicies
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/StoragePolicies'

definitions:
  StoragePolicy:
    x-vcloud-added-in: "36.0"
    description: |
      A Provider Storage Policy.
    type: object
    properties:
      id:
        type: string
        description: "Unique VCD Id for the Storage Policy."
      name:
        type: string
        description: "Name for the Storage Policy."
    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: NonSortable
          - constraint: Urn
            args:
              - arg: storagepolicy
      name:
        x-vcloud-constraints:
          - constraint: ReadOnly

  StoragePolicies:
    x-vcloud-added-in: "36.0"
    description: |
      A list of Storage Policies.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            description: The current page of Storage Policies.
            items:
              $ref: '#/definitions/StoragePolicy'
