# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The vCloud Director Org API.
  version: "1.0"
  title: vCloud Director Org API

paths:

  orgs:
    get:
      tags:
        - Org
      summary: Get list of all orgs accessible to the user.
      x-vcloud-added-in: "35.0"
      x-vcloud-multisite: true
      x-vcloud-default-sort:
        default-sort-field: name
        sort-ascending: true
      description: |
        Get list of all orgs accessible to the user.
      operationId: queryOrgs
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Orgs'

    post:
      tags:
        - Org
      summary: Create a new organization
      x-vcloud-added-in: "36.0"
      operationId: createOrg
      consumes:
        - application/json
      parameters:
        - name: newOrg
          in: body
          required: true
          schema:
            $ref: "#/definitions/Org"
      produces:
        - application/json
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Org"

  org:
    parameters:
      - name: orgUrn
        in: path
        description: orgUrn
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: org
    get:
      x-vcloud-added-in: "35.0"
      tags:
        - Org
      summary: Get specified organization.
      operationId: getOrg
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Org"
    delete:
      tags:
        - Org
      summary: Delete the specified org.
      operationId: deleteOrg
      parameters:
        - $ref: "./common/delete.yaml#/parameters/forceDelete"
          description: "Pass force=true as query parameter to remove an organization regardless of its state."
        - $ref: "./common/delete.yaml#/parameters/recursiveDelete"
          description: "Pass recursive=true as query parameter to remove an organization and any objects it contains."
      x-vcloud-added-in: "36.0"
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
    put:
      tags:
        - Org
      summary: Updates an organization.
      x-vcloud-added-in: "36.0"
      description: |
        Updates an organization.
      operationId: updateOrg
      consumes:
        - application/json
      parameters:
        - name: modifiedOrg
          in: body
          required: true
          schema:
            $ref: "#/definitions/Org"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Org"

definitions:

  Org:
    x-vcloud-added-in: "35.0"
    description: |
      An Organization.
    type: object
    properties:
      id:
        type: string
        description: A unique identifier for the organization.
      name:
        type: string
        description: Name of the organization.
        pattern: "^[a-zA-Z0-9_\\-\\.\\!\\'\\(\\),\\$]+$"
        maxLength: 128
      displayName:
        type: string
        description: Full display name of the organization.
        pattern: "(?=.*\\S.*)^[^\\p{Zl}\\p{Zp}\\p{C}]*$"
        maxLength: 128
      description:
        type: string
        default: ""
        description: Description of the organization.
        maxLength: 256
      isEnabled:
        type: boolean
        default: false
        description: Whether the organization is enabled or not.
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
      orgVdcCount:
        type: integer
        description: The number of VDCs in the org.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
      catalogCount:
        type: integer
        description: The number of catalogs in the org.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
      vappCount:
        type: integer
        description: The number of vApps in the org.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
      runningVMCount:
        type: integer
        description: The number of running VMs in the org.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
      userCount:
        type: integer
        description: The number of users in the org.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
      canPublish:
        type: boolean
        description: Whether the organization can publish catalogs externally.
        x-vcloud-added-in: "36.0"
        x-vcloud-restricted: restricted field, requires "Organization Administrator View" right to access this field.
        x-vcloud-constraints:
          - constraint: ReadOnly
    required:
      - name
      - displayName
  x-vcloud-property-annotations:
    id:
      x-vcloud-constraints:
        - constraint: NonSortable
        - constraint: Urn
        - constraint: ReadOnly
          args:
            - arg: org
  Orgs:
    x-vcloud-added-in: "35.0"
    description: |
      A list of Organizations.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            description: The current page of organizations.
            items:
              $ref: '#/definitions/Org'
